services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    healthcheck:
      disable: true
    ports:
      - "${PORT}:${PORT}"
      - "9229:9229" # Debugging port (Node.js)
    volumes:
      - .:/app
      - ./downloads:/home/pwuser/downloads
      - /Users/kanegadai/.ssh/gcp/cat-observes-1250b9d70c39.json:/app/gcp-key.json
    env_file:
      - .env
      - .env.development.local
    # 開発環境用：Dockerfile の CMD ["xvfb-run", "--server-args=-screen 0 1920x1080x24", "node", "dist/main"] を上書き
    # 開発環境では Dockerfile の xvfb-run 不要：
    # • ホストマシンのディスプレイが利用可
    # • VSCode Dev Container が X11 フォワーディングをサポート
    # • ホストとソースコードが同期（ホットリロード有効）
    # • デバッグ機能が利用可能（ブレークポイント、ソースマップ等）
    command: npm run debug
