services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV} # 環境変数
        PORT: ${PORT} # 環境変数
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.development.local # todo: 開発環境のコンテナ化のため、一時的に追加。あとで消す
    command: npm run start:dev
