services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    healthcheck:
      disable: true
    ports:
      - "${PORT}:${PORT}"
      - "9229:9229" # Debugging port (Node.js)
    volumes:
      - .:/app
      - ./downloads:/home/pwuser/downloads
      - /Users/kanegadai/.ssh/gcp/cat-observes-1250b9d70c39.json:/app/gcp-key.json
    env_file:
      - .env
      - .env.development.local
    command: npm run debug
